version: '3.8'

services:
  bff:
    build:
      context: ./bff
    ports:
      - "5000:5000"
    networks:
      - my-network

  api:
    build:
      context: ./api
    depends_on:
      - bff
    networks:
      - my-network

networks:
  my-network:
    driver: bridge